apiVersion: v1
kind: Pod
spec:
  containers:
  - name: nodejs
    image: node:18-alpine3.17
    command:
    - cat
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
      - sleep
    args:
    - 99d
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker 
  volumes:
  - name: kaniko-secret
    secret:
      secretName: kaniko-secret